/**
 * Sample site data — field names aligned with the PHP toplist CMS
 * so this template can later wire to JSON APIs.
 */
window.SITE = {
  name: "TopList",
  tagline: "Curated best-of directories for people who actually ship.",
  year: new Date().getFullYear(),
  homeTitle: "The best websites, ranked",
  homeSubtitle: "Hand-picked tools and destinations across learning, productivity, AI, and more.",
  editorialDisclaimer:
    "Rankings are editorial and may include affiliate partnerships. Always verify a site before you commit time or money.",
  bottomBlock: {
    enabled: true,
    title: "Discover more ranked lists",
    text: "Browse every category — learning, productivity, AI tools, and developer resources.",
    ctaLabel: "View all categories",
    ctaHref: "index.html",
    image: "https://picsum.photos/seed/toplist-promo/1200/360",
  },
};

window.CATEGORIES = [
  {
    id: 1,
    name: "Free Learning",
    slug: "free-learning",
    description:
      "World-class courses and lessons you can start today without a credit card.",
    introText: "About Free Learning",
    accent: "#0d9488",
    emoji: "📚",
    sortOrder: 1,
  },
  {
    id: 2,
    name: "Productivity",
    slug: "productivity",
    description: "Apps that cut noise and help you finish the work that matters.",
    introText: "About Productivity",
    accent: "#2563eb",
    emoji: "⚡",
    sortOrder: 2,
  },
  {
    id: 3,
    name: "AI Image Tools",
    slug: "ai-image-tools",
    description: "Generators and editors for concept art, mockups, and creative experiments.",
    introText: "About AI Image Tools",
    accent: "#c2410c",
    emoji: "🎨",
    sortOrder: 3,
  },
  {
    id: 4,
    name: "Developer Resources",
    slug: "developer-resources",
    description: "Docs, sandboxes, and references developers keep open all day.",
    introText: "About Developer Resources",
    accent: "#0f766e",
    emoji: "💻",
    sortOrder: 4,
  },
  {
    id: 5,
    name: "News & Media",
    slug: "news-media",
    description: "Reliable reporting and sharp analysis without the doomscroll trap.",
    introText: "About News & Media",
    accent: "#b45309",
    emoji: "📰",
    sortOrder: 5,
  },
  {
    id: 6,
    name: "Crypto Wallets",
    slug: "crypto-wallets",
    description: "Self-custody options with clear trade-offs for everyday use.",
    introText: "About Crypto Wallets",
    accent: "#059669",
    emoji: "🔐",
    sortOrder: 6,
  },
];

window.ENTRIES = [
  // Free Learning
  {
    id: 101,
    categoryId: 1,
    name: "Khan Academy",
    slug: "khan-academy",
    url: "https://www.khanacademy.org/",
    affiliateUrl: "",
    description: "Mastery-based lessons across math, science, and the humanities.",
    reviewContent:
      "Khan Academy remains the gold standard for free structured learning. Clear explanations, practice loops, and progress tracking make it ideal for students and self-learners alike.",
    rating: 5.0,
    pros: ["Completely free", "Excellent practice system", "Wide subject coverage"],
    cons: ["UI can feel dated", "Limited advanced CS tracks"],
    thumb: "https://picsum.photos/seed/khan/800/450",
    sortOrder: 1,
    isNew: true,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 102,
    categoryId: 1,
    name: "Coursera",
    slug: "coursera",
    url: "https://www.coursera.org/",
    affiliateUrl: "",
    description: "University and industry courses with optional certificates.",
    reviewContent:
      "Coursera bridges university rigor and online flexibility. Audit many courses for free, then upgrade when you need credentials.",
    rating: 4.7,
    pros: ["Top university partners", "Career certificates", "Flexible pacing"],
    cons: ["Certificates cost money", "Quality varies by course"],
    thumb: "https://picsum.photos/seed/coursera/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 103,
    categoryId: 1,
    name: "freeCodeCamp",
    slug: "freecodecamp",
    url: "https://www.freecodecamp.org/",
    affiliateUrl: "",
    description: "Hands-on coding curriculum with projects and certifications.",
    reviewContent:
      "If you want to learn to code by building, freeCodeCamp is hard to beat. The curriculum is long-form and practical.",
    rating: 4.9,
    pros: ["Project-based", "Active community", "Truly free certs"],
    cons: ["Less hand-holding", "Pacing is self-driven"],
    thumb: "https://picsum.photos/seed/fcc/800/450",
    sortOrder: 3,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 104,
    categoryId: 1,
    name: "OpenLearn",
    slug: "openlearn",
    url: "https://www.open.edu/openlearn/",
    affiliateUrl: "",
    description: "Free courses from The Open University across dozens of topics.",
    reviewContent:
      "OpenLearn is a quiet gem for curious adults — short courses with academic DNA and no signup wall for browsing.",
    rating: 4.5,
    pros: ["OU-backed content", "Broad topics", "Bite-sized options"],
    cons: ["Less interactive than peers", "Certificates limited"],
    thumb: "https://picsum.photos/seed/openlearn/800/450",
    sortOrder: 4,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 105,
    categoryId: 1,
    name: "Brilliant",
    slug: "brilliant",
    url: "https://brilliant.org/",
    affiliateUrl: "",
    description: "Interactive problem-solving for math, science, and CS.",
    reviewContent:
      "Brilliant teaches through interactive puzzles. Great for building intuition; less ideal if you need formal lecture notes.",
    rating: 4.6,
    pros: ["Highly interactive", "Beautiful UX", "Strong STEM focus"],
    cons: ["Premium for full access", "Narrower subject set"],
    thumb: "https://picsum.photos/seed/brilliant/800/450",
    sortOrder: 5,
    isNew: true,
    isFeatured: false,
    isAi: false,
  },

  // Productivity
  {
    id: 201,
    categoryId: 2,
    name: "Notion",
    slug: "notion",
    url: "https://www.notion.so/",
    affiliateUrl: "",
    description: "All-in-one workspace for notes, wikis, and light databases.",
    reviewContent:
      "Notion is the default second brain for many teams. Flexible blocks win; performance can dip on huge workspaces.",
    rating: 4.8,
    pros: ["Extremely flexible", "Great templates", "Solid free tier"],
    cons: ["Can get messy", "Offline still limited"],
    thumb: "https://picsum.photos/seed/notion/800/450",
    sortOrder: 1,
    isNew: false,
    isFeatured: true,
    isAi: true,
  },
  {
    id: 202,
    categoryId: 2,
    name: "Todoist",
    slug: "todoist",
    url: "https://todoist.com/",
    affiliateUrl: "",
    description: "Fast task manager with natural-language due dates.",
    reviewContent:
      "Todoist stays out of the way. Capture is fast, Karma keeps motivation, and cross-platform sync is reliable.",
    rating: 4.7,
    pros: ["Quick capture", "Natural language", "Clean apps"],
    cons: ["Advanced features gated", "No deep notes"],
    thumb: "https://picsum.photos/seed/todoist/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 203,
    categoryId: 2,
    name: "Google Keep",
    slug: "google-keep",
    url: "https://keep.google.com/",
    affiliateUrl: "",
    description: "Lightweight notes and checklists synced with Google.",
    reviewContent:
      "Keep is perfect for sticky-note thinking. Color labels and reminders shine; power users will outgrow it.",
    rating: 4.3,
    pros: ["Dead simple", "Free with Google", "Great reminders"],
    cons: ["Limited structure", "Weak collaboration"],
    thumb: "https://picsum.photos/seed/keep/800/450",
    sortOrder: 3,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 204,
    categoryId: 2,
    name: "Linear",
    slug: "linear",
    url: "https://linear.app/",
    affiliateUrl: "",
    description: "Issue tracking built for high-velocity product teams.",
    reviewContent:
      "Linear feels like a keyboard-first IDE for project work. Keyboard shortcuts and polish set it apart from Jira-era tools.",
    rating: 4.9,
    pros: ["Blazing fast UI", "Excellent shortcuts", "Clean roadmaps"],
    cons: ["Team-oriented pricing", "Overkill for solo tasks"],
    thumb: "https://picsum.photos/seed/linear/800/450",
    sortOrder: 4,
    isNew: true,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 205,
    categoryId: 2,
    name: "Obsidian",
    slug: "obsidian",
    url: "https://obsidian.md/",
    affiliateUrl: "",
    description: "Local-first Markdown knowledge base with graph links.",
    reviewContent:
      "Obsidian owns the local-first PKM niche. Plugins are endless; the learning curve is real.",
    rating: 4.8,
    pros: ["Local Markdown files", "Huge plugin ecosystem", "Graph view"],
    cons: ["Steep setup", "Sync is paid"],
    thumb: "https://picsum.photos/seed/obsidian/800/450",
    sortOrder: 5,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },

  // AI Image Tools
  {
    id: 301,
    categoryId: 3,
    name: "Midjourney",
    slug: "midjourney",
    url: "https://www.midjourney.com/",
    affiliateUrl: "",
    description: "High-end generative art with a distinctive aesthetic.",
    reviewContent:
      "Midjourney still leads for tasteful, coherent imagery. Discord-centric workflow is a love-or-hate interface.",
    rating: 4.8,
    pros: ["Stunning output", "Strong style control", "Active community"],
    cons: ["Subscription required", "Discord-first UX"],
    thumb: "https://picsum.photos/seed/midjourney/800/450",
    sortOrder: 1,
    isNew: false,
    isFeatured: true,
    isAi: true,
  },
  {
    id: 302,
    categoryId: 3,
    name: "Adobe Firefly",
    slug: "adobe-firefly",
    url: "https://firefly.adobe.com/",
    affiliateUrl: "",
    description: "Generative fill and image tools integrated with Creative Cloud.",
    reviewContent:
      "Firefly is the safest pick for commercial creatives already in Adobe’s stack, with clearer training-data claims.",
    rating: 4.5,
    pros: ["CC integration", "Commercial-friendly stance", "Familiar tools"],
    cons: ["Best with paid plan", "Less wild than Midjourney"],
    thumb: "https://picsum.photos/seed/firefly/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: false,
    isAi: true,
  },
  {
    id: 303,
    categoryId: 3,
    name: "Leonardo AI",
    slug: "leonardo-ai",
    url: "https://leonardo.ai/",
    affiliateUrl: "",
    description: "Game-art focused generator with fine model control.",
    reviewContent:
      "Leonardo is strong for game assets and consistent character sheets. Token economy rewards regular use.",
    rating: 4.4,
    pros: ["Asset-oriented models", "Canvas tools", "Daily tokens"],
    cons: ["UI density", "Quality varies by model"],
    thumb: "https://picsum.photos/seed/leonardo/800/450",
    sortOrder: 3,
    isNew: true,
    isFeatured: false,
    isAi: true,
  },
  {
    id: 304,
    categoryId: 3,
    name: "Craiyon",
    slug: "craiyon",
    url: "https://www.craiyon.com/",
    affiliateUrl: "",
    description: "Free, fast image generation for casual experiments.",
    reviewContent:
      "Craiyon is the zero-friction playground. Results are rougher, but the free barrier is nearly nonexistent.",
    rating: 3.9,
    pros: ["Free to try", "No install", "Fun for drafts"],
    cons: ["Lower fidelity", "Ads on free tier"],
    thumb: "https://picsum.photos/seed/craiyon/800/450",
    sortOrder: 4,
    isNew: false,
    isFeatured: false,
    isAi: true,
  },

  // Developer Resources
  {
    id: 401,
    categoryId: 4,
    name: "MDN Web Docs",
    slug: "mdn-web-docs",
    url: "https://developer.mozilla.org/",
    affiliateUrl: "",
    description: "The canonical reference for HTML, CSS, and JavaScript.",
    reviewContent:
      "MDN is the first tab for web platform questions. Accurate, maintained, and still the best deep-dive docs.",
    rating: 5.0,
    pros: ["Authoritative", "Great examples", "Always free"],
    cons: ["Can be dense for beginners"],
    thumb: "https://picsum.photos/seed/mdn/800/450",
    sortOrder: 1,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 402,
    categoryId: 4,
    name: "GitHub",
    slug: "github",
    url: "https://github.com/",
    affiliateUrl: "",
    description: "Code hosting, collaboration, and the open-source social graph.",
    reviewContent:
      "GitHub is infrastructure. Actions, Codespaces, and search make it more than a git host.",
    rating: 4.9,
    pros: ["Ubiquitous", "CI & collaboration", "Huge ecosystem"],
    cons: ["Pricing tiers add up", "UI complexity"],
    thumb: "https://picsum.photos/seed/github/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: true,
    isAi: true,
  },
  {
    id: 403,
    categoryId: 4,
    name: "Stack Overflow",
    slug: "stack-overflow",
    url: "https://stackoverflow.com/",
    affiliateUrl: "",
    description: "Q&A archive that still saves debugging weekends.",
    reviewContent:
      "Stack Overflow’s archive is unmatched. The culture can be sharp, but the answers endure.",
    rating: 4.4,
    pros: ["Massive archive", "Fast search hits", "Community voting"],
    cons: ["Can feel unwelcoming", "Some answers outdated"],
    thumb: "https://picsum.photos/seed/stackoverflow/800/450",
    sortOrder: 3,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 404,
    categoryId: 4,
    name: "Can I use",
    slug: "caniuse",
    url: "https://caniuse.com/",
    affiliateUrl: "",
    description: "Browser support tables for modern web features.",
    reviewContent:
      "Before shipping a CSS or JS feature, Can I use is the sanity check. Simple, essential, trustworthy.",
    rating: 4.8,
    pros: ["Clear support matrices", "Always relevant", "Fast"],
    cons: ["Narrow scope by design"],
    thumb: "https://picsum.photos/seed/caniuse/800/450",
    sortOrder: 4,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 405,
    categoryId: 4,
    name: "Programiz",
    slug: "programiz",
    url: "https://www.programiz.com/",
    affiliateUrl: "",
    description: "Beginner-friendly tutorials and online compilers.",
    reviewContent:
      "Programiz is a friendly on-ramp for new programmers, with in-browser compilers that remove setup friction.",
    rating: 4.3,
    pros: ["Beginner friendly", "Online compilers", "Many languages"],
    cons: ["Less depth than MDN", "Ads on free pages"],
    thumb: "https://picsum.photos/seed/programiz/800/450",
    sortOrder: 5,
    isNew: true,
    isFeatured: false,
    isAi: false,
  },

  // News & Media
  {
    id: 501,
    categoryId: 5,
    name: "Associated Press",
    slug: "associated-press",
    url: "https://apnews.com/",
    affiliateUrl: "",
    description: "Straight wire reporting used by newsrooms worldwide.",
    reviewContent:
      "AP is the calm baseline for breaking news. Expect facts first, opinion later — usually elsewhere.",
    rating: 4.7,
    pros: ["High trust", "Fast wire", "Global coverage"],
    cons: ["Sparse analysis", "Dry tone"],
    thumb: "https://picsum.photos/seed/apnews/800/450",
    sortOrder: 1,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 502,
    categoryId: 5,
    name: "Axios",
    slug: "axios",
    url: "https://www.axios.com/",
    affiliateUrl: "",
    description: "Smart brevity — news cards built for busy readers.",
    reviewContent:
      "Axios invented a readable format for people who skim. Bullet-first storytelling without feeling empty.",
    rating: 4.5,
    pros: ["Scannable format", "Strong politics/tech", "Newsletters"],
    cons: ["Paywalled depth", "Less international depth"],
    thumb: "https://picsum.photos/seed/axios/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 503,
    categoryId: 5,
    name: "The Hill",
    slug: "the-hill",
    url: "https://thehill.com/",
    affiliateUrl: "",
    description: "Capitol Hill coverage with rapid political updates.",
    reviewContent:
      "The Hill is a go-to for US political process coverage. Fast updates; pair with deeper outlets for context.",
    rating: 4.2,
    pros: ["Hill-focused", "Frequent updates", "Free reading"],
    cons: ["US-centric", "Headline noise"],
    thumb: "https://picsum.photos/seed/thehill/800/450",
    sortOrder: 3,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 504,
    categoryId: 5,
    name: "Bloomberg",
    slug: "bloomberg",
    url: "https://www.bloomberg.com/",
    affiliateUrl: "",
    description: "Markets, business, and global economic reporting.",
    reviewContent:
      "Bloomberg sets the pace for markets news. The free layer is useful; terminal-grade depth sits behind paywalls.",
    rating: 4.6,
    pros: ["Market authority", "Data-rich", "Global desk"],
    cons: ["Heavy paywall", "Dense for casual readers"],
    thumb: "https://picsum.photos/seed/bloomberg/800/450",
    sortOrder: 4,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },

  // Crypto Wallets
  {
    id: 601,
    categoryId: 6,
    name: "MetaMask",
    slug: "metamask",
    url: "https://metamask.io/",
    affiliateUrl: "",
    description: "Browser and mobile wallet for Ethereum and EVM chains.",
    reviewContent:
      "MetaMask is the default EVM wallet. Ubiquitous dApp support; phishing remains the user’s responsibility.",
    rating: 4.5,
    pros: ["Everywhere support", "Easy browser UX", "Huge ecosystem"],
    cons: ["Phishing risk", "Seed phrase UX"],
    thumb: "https://picsum.photos/seed/metamask/800/450",
    sortOrder: 1,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 602,
    categoryId: 6,
    name: "Ledger",
    slug: "ledger",
    url: "https://www.ledger.com/",
    affiliateUrl: "",
    description: "Hardware wallets for offline key storage.",
    reviewContent:
      "Ledger is the hardware standard for many long-term holders. Device + app workflow is mature and well documented.",
    rating: 4.6,
    pros: ["Cold storage", "Wide coin support", "Mature product"],
    cons: ["Hardware cost", "Setup friction"],
    thumb: "https://picsum.photos/seed/ledger/800/450",
    sortOrder: 2,
    isNew: false,
    isFeatured: true,
    isAi: false,
  },
  {
    id: 603,
    categoryId: 6,
    name: "Phantom",
    slug: "phantom",
    url: "https://phantom.app/",
    affiliateUrl: "",
    description: "Polished wallet for Solana and expanding multi-chain use.",
    reviewContent:
      "Phantom made Solana wallets feel consumer-grade. Clean UX and growing multi-chain ambitions.",
    rating: 4.4,
    pros: ["Excellent UX", "Solana native", "Mobile + extension"],
    cons: ["Less EVM history", "Newer multi-chain story"],
    thumb: "https://picsum.photos/seed/phantom/800/450",
    sortOrder: 3,
    isNew: true,
    isFeatured: false,
    isAi: false,
  },
  {
    id: 604,
    categoryId: 6,
    name: "Trezor",
    slug: "trezor",
    url: "https://trezor.io/",
    affiliateUrl: "",
    description: "Open-source hardware wallets with transparent firmware.",
    reviewContent:
      "Trezor appeals to users who want open hardware and a straightforward recovery model. A solid Ledger alternative.",
    rating: 4.5,
    pros: ["Open approach", "Trusted brand", "Clear UX"],
    cons: ["Fewer models", "Hardware cost"],
    thumb: "https://picsum.photos/seed/trezor/800/450",
    sortOrder: 4,
    isNew: false,
    isFeatured: false,
    isAi: false,
  },
];
